/**
 * AM Business Platform - Phase 2.6 General Ledger & Financial Closing Domain Types
 * Aligned with SAP S/4HANA FI-GL, Oracle ERP Cloud GL, D365 Finance, IFRS, IAS 1, IAS 8, IAS 21
 */

import { AccountingDimensions } from './index';

export type GLAccountGroup = 
  | 'Assets' 
  | 'Liabilities' 
  | 'Equity' 
  | 'Revenue' 
  | 'CostOfSales' 
  | 'OperatingExpense' 
  | 'OtherIncomeExpense';

export type GLAccountType = 
  | 'Cash' 
  | 'Receivable' 
  | 'Payable' 
  | 'Inventory' 
  | 'TaxPayable' 
  | 'TaxReceivable' 
  | 'Equity' 
  | 'RetainedEarnings' 
  | 'Revenue' 
  | 'COGS' 
  | 'OperatingExpense' 
  | 'FixedAsset' 
  | 'AccumulatedDepreciation';

export type GLPostingRestriction = 
  | 'POSTING_ALLOWED' 
  | 'CONTROL_ACCOUNT_ONLY' 
  | 'STATISTICAL_ONLY' 
  | 'READ_ONLY' 
  | 'BLOCKED';

export interface GLAccount {
  id: string;
  tenantId: string;
  companyId: string;
  code: string;
  name: string;
  nameAr: string;
  group: GLAccountGroup;
  accountType: GLAccountType;
  parentId: string | null;
  level: number;
  isControlAccount: boolean;
  controlType?: 'AR' | 'AP' | 'INV' | 'TAX' | 'BANK';
  postingRestriction: GLPostingRestriction;
  currency: string;
  balance: number;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export type GLJournalType = 
  | 'OPENING'
  | 'MANUAL' 
  | 'AUTOMATIC' 
  | 'FINANCIAL_EVENT' 
  | 'RECURRING' 
  | 'REVERSING';

export type GLJournalStatus = 
  | 'DRAFT' 
  | 'POSTED' 
  | 'CANCELLED' 
  | 'REVERSED';

export interface GLJournalLine {
  id: string;
  lineNo: number;
  accountCode: string;
  accountName: string;
  description: string;
  debit: number;
  credit: number;
  currency?: string;
  exchangeRate?: number;
  baseCurrencyDebit?: number;
  baseCurrencyCredit?: number;
  dimensions?: AccountingDimensions;
}

export interface GLJournalEntry {
  id: string;
  tenantId: string;
  companyId: string;
  branchId?: string;
  entryNumber: string; // e.g. JE-2026-0001
  date: string;
  postingDate: string;
  fiscalYear: number;
  fiscalPeriod: number;
  journalType: GLJournalType;
  status: GLJournalStatus;
  reference?: string;
  description: string;
  totalDebit: number;
  totalCredit: number;
  currency: string;
  exchangeRate: number;
  lines: GLJournalLine[];
  isAutoGenerated: boolean;
  originatingDocumentType?: string;
  originatingDocumentId?: string;
  originatingDocumentNumber?: string;
  isReversing?: boolean;
  reversalDate?: string;
  reversedJournalEntryId?: string;
  isReversed?: boolean;
  recurringScheduleId?: string;
  createdBy: string;
  createdByName: string;
  createdAt: string;
  approvedBy?: string;
  approvedAt?: string;
  updatedAt?: string;
  idempotencyKey?: string;
  auditHash: string; // SHA-256
  correlationId: string;
}

export interface FiscalYearRecord {
  id: string;
  tenantId: string;
  companyId: string;
  year: number;
  startDate: string;
  endDate: string;
  isClosed: boolean;
  closedAt?: string;
  closedBy?: string;
}

export type FiscalPeriodStatus = 'OPEN' | 'CLOSING' | 'CLOSED' | 'REOPENED';

export interface FiscalPeriodRecord {
  id: string;
  tenantId: string;
  companyId: string;
  fiscalYearId: string;
  year: number;
  periodNumber: number; // 1 to 12 or 13 (Year-End Close)
  periodName: string;
  startDate: string;
  endDate: string;
  status: FiscalPeriodStatus;
  lockedBy?: string;
  lockedAt?: string;
  reopenCounter?: number;
  lastReopenedReason?: string;
  lastReopenedBy?: string;
  lastReopenedAt?: string;
}

export interface RecurringJournalSchedule {
  id: string;
  tenantId: string;
  companyId: string;
  scheduleCode: string;
  name: string;
  frequency: 'MONTHLY' | 'QUARTERLY' | 'YEARLY';
  nextExecutionDate: string;
  lastExecutedDate?: string;
  startDate: string;
  endDate?: string;
  isActive: boolean;
  description: string;
  templateLines: GLJournalLine[];
  createdBy: string;
  createdAt: string;
}

export interface TrialBalanceRow {
  accountCode: string;
  accountName: string;
  accountGroup: GLAccountGroup;
  accountType: GLAccountType;
  isControlAccount: boolean;
  openingDebit: number;
  openingCredit: number;
  openingNet: number;
  periodDebit: number;
  periodCredit: number;
  closingDebit: number;
  closingCredit: number;
  closingNet: number;
}

export interface TrialBalanceIntegrityReport {
  isVerified: boolean;
  totalOpeningDebit: number;
  totalOpeningCredit: number;
  totalPeriodDebit: number;
  totalPeriodCredit: number;
  totalClosingDebit: number;
  totalClosingCredit: number;
  accountCount: number;
  accountDiscrepancies: Array<{
    accountCode: string;
    expectedClosingNet: number;
    actualClosingNet: number;
    diff: number;
  }>;
  sha256VerificationHash: string;
}

export interface SuspenseAccountReport {
  hasUnresolvedSuspense: boolean;
  suspenseAccounts: Array<{
    accountCode: string;
    accountName: string;
    accountType: string;
    balance: number;
    status: 'CLEARED' | 'UNRESOLVED_BALANCE';
  }>;
}

export interface FinancialCloseChecklist {
  periodId: string;
  periodName: string;
  year: number;
  isAllEventsProcessed: boolean;
  isSubledgersReconciled: boolean;
  isUnpostedJournalsCleared: boolean;
  isTrialBalanceBalanced: boolean;
  isForeignCurrencyRevalued: boolean;
  isApprovedByController: boolean;
  isInventoryClosed: boolean;
  isProcurementClosed: boolean;
  isAPClosed: boolean;
  isARClosed: boolean;
  isFinancialEventQueueEmpty: boolean;
  isSuspenseAccountsCleared: boolean;
  canClose: boolean;
  blockers: string[];
}

export interface YearEndClosingRecord {
  id: string;
  tenantId: string;
  companyId: string;
  fiscalYear: number;
  closingDate: string;
  netIncomeOrLoss: number;
  retainedEarningsAccountCode: string;
  retainedEarningsJournalEntryId: string;
  openingBalancesGenerated: boolean;
  closedBy: string;
  closedAt: string;
  auditHash: string;
}

export interface IAS21RevaluationResult {
  accountCode: string;
  accountName: string;
  currency: string;
  foreignBalance: number;
  historicalBookRate: number;
  historicalBaseAmount: number;
  periodEndSpotRate: number;
  revaluedBaseAmount: number;
  unrealizedGainLoss: number; // Positive = Gain, Negative = Loss
}

export interface IAS21FXSnapshotRecord {
  id: string;
  tenantId: string;
  companyId: string;
  valuationDate: string;
  spotRates: Record<string, number>;
  revaluationResults: IAS21RevaluationResult[];
  totalUnrealizedGainLoss: number;
  createdBy: string;
  createdAt: string;
  sha256Hash: string;
  correlationId: string;
}

export interface ClosingSnapshotRecord {
  id: string;
  tenantId: string;
  companyId: string;
  periodId: string;
  periodName: string;
  year: number;
  closedBy: string;
  closedAt: string;
  chartOfAccountsSnapshot: GLAccount[];
  trialBalanceSnapshot: TrialBalanceRow[];
  journalEntriesCount: number;
  fxRatesSnapshot: Record<string, number>;
  sha256Hash: string;
  correlationId: string;
}

export interface GLAuditRecord {
  id: string;
  tenantId: string;
  companyId: string;
  timestamp: string;
  userId: string;
  userName: string;
  action: 
    | 'ACCOUNT_CREATED' 
    | 'ACCOUNT_UPDATED' 
    | 'JOURNAL_CREATED' 
    | 'JOURNAL_POSTED' 
    | 'JOURNAL_REVERSED' 
    | 'PERIOD_CLOSED' 
    | 'PERIOD_REOPENED' 
    | 'YEAR_END_CLOSED'
    | 'RECURRING_EXECUTED'
    | 'FX_REVALUED'
    | 'AUTOMATIC_POSTING';
  entityType: 'GLAccount' | 'GLJournal' | 'FiscalPeriod' | 'FiscalYear' | 'IAS21Snapshot' | 'ClosingSnapshot';
  entityId: string;
  correlationId: string;
  hash: string;
  details: string;
}
